const Map<String, String> enUS = {
  "Enter_Valid_Email": "Enter a Valid Email",
  "Log_In": "Log In",
  "please_check_credentials": "please check credentials",
  "Sing_UP": "Sing UP",
  "Today_Activities": "Today Activities",
  "Today_Found": "Today Activites Not Found",
  "Add_Activites": "Add Activites",
  "Enter_Content": "Enter Content",
  "Choose_Date": "Choose Date",
  "Add_Todo": "Add Todo",
  "Empty_List": "Empty List",
  "Add_Farm": "Add Farm",
  "Please_select_image": "Please select image",
  "Add_Member": "Add Member",
  "want_delete": "Are you sure, do you want to Delete ?",
  "Enter_Description": "Enter Description",
  "Enter_amount": "Enter amount",
  "Date_Birth": "Date Of Birth",
  "Item_Category": "Item Category",
  "Sub_Category": "Sub Category",
  "Please_Select_Image": "Please Select Image",
  "Cannot_Select_Image": "Cannot  Select Image",
  "Change_Profile": "Change Profile",
  "want_logout": "Are you sure, do you want to Logout ?",
  "My_Posts": "My Posts",
  "Edit_Post": "Edit Post",
  "Sign_Up_Failed": "Sign Up Failed",
  "Cannot_add_item": "Cannot add this item",
  "was_added_cart": "was added to your cart",
  "Cannot_remove_item": "Cannot remove this item",
  "Updated_Profile_Name": "Updated to Profile Name",
  "was_Updated_arm": "was Updated to your farm",
  "Add_Post": "Add Post",
  "seavrch": "തിരയുക",
  "sezcarch": "തിരയുക",
  "Seattings": "ക്രമീകരണങ്ങൾ",
  "WELqCOME": "സ്വാഗതം",
  "sefardchf": "തിരയുക",
  "seafdrch": "തിരയുക",
  "seacsrch": "തിരയുക",
  "secasrch": "തിരയുക",
  "seaxrsch": "തിരയുക",
  "sezarsch": "തിരയുക",
  "seavsrch": "തിരയുക",
  "seszcarch": "തിരയുക",
};
