const Map<String, String> hiIN = {
  "Settings": "समायोजन",
  "WELCOME": "स्वागत हे",
  "Skip": "छोड़ें",
  "Enter_Password": "पास वर्ड दर्ज करें",
  "Password": "पास वर्ड",
  "Email": "ईमेल",
  "Enter_Email_ID": "ईमेल आईडी दर्ज करें",
  "Enter_Valid_Email": "एक वैध ईमेल प्रविष्ट करें",
  "Log_In": "लॉग इन करें",
  "please_check_credentials": "कृपया क्रेडेंशियल जांचें",
  "Sing_UP": "जोर से गाना",
  "Add": "जोड़ें",
  "Today_Activities": "आज की गतिविधियां",
  "Today_Found": "आज की गतिविधियां नहीं मिली",
  "Add_Activites": "गतिविधियां जोड़ें",
  "Cancel": "रद्द करें",
  "Content": "विषय",
  "Enter_Content": "सामग्री दर्ज करें",
  "Date": "तारीख",
  "Add_Todo": "टोडो जोड़ें",
  "Loading": "लोड हो रहा है",
  "Empty_List": "खाली सूची",
  "Add_Farm": "फार्म जोड़ें",
  "Name": "नाम",
  "Enter_Name": "नाम दर्ज करें",
  "Camera": "कैमरा",
  "Gallery": "गेलरी",
  "Please_select_image": "कृपया छवि का चयन करें",
  "SUBMIT": "प्रस्तुत",
  "Tottal": "टोटल",
  "Add_Member": "सदस्य जोड़ें",
  "want_delete": "क्या आप सुनिश्चित हैं, क्या आप हटाना चाहते हैं?",
  "Yes": "हां",
  "No": "नहीं",
  "Members": "सदस्यों",
  "expense": "व्यय",
  "profite": "मुनाफाखोरी",
  "losse": "हानि",
  "more": "अधिक",
  "Description": "विवरण",
  "Enter_Description": "विवरण दर्ज करें",
  "Enter_amount": "राशी डालें",
  "Notification": "अधिसूचना",
  "Id": "पहचान",
  "Enter_ID": "आईडी दर्ज करें",
  "Date_Birth": "जन्म की तारीख",
  "Item_Category": "आइटम श्रेणी",
  "Sub_Category": "उप श्रेणी",
  "Please_Select_Image": "कृपया छवि का चयन करें",
  "Cannot_Select_Image": "छवि का चयन नहीं कर सकता",
  "Explore": "अन्वेषण करना",
  "Edit": "संपादित करें",
  "Change_Profile": "विवरणिका बदले",
  "Logout": "लॉग आउट",
  "want_logout": "क्या आप निश्चित हैं, क्या आप लॉगआउट करना चाहते हैं?",
  "My_Posts": "मेरी पोस्ट",
  "Edit_Post": "संपादित पोस्ट",
  "Sign_Up_Failed": "साइन अप विफल रहा",
  "Error": "त्रुटि",
  "Cannot_add_item": "इस आइटम को नहीं जोड़ सकते",
  "Item_added": "आइटम जोड़ा गया",
  "was_added_cart": "आपके कार्ट में जोड़ा गया था",
  "Cannot_remove_item": "इस आइटम को हटा नहीं सकते",
  "Upadated": "अद्यतन",
  "Updated_Profile_Name": "प्रोफ़ाइल नाम में अपडेट किया गया",
  "Add_Post": "पोस्ट जोड़ें",
  "sezcarch": "തിരയുക",
};
