const Map<String, String> mlIN = {
  "Settings": "ക്രമീകരണങ്ങൾ",
  "WELCOME": "സ്വാഗതം",
  "sefarchf": "തിരയുക",
  "seafrch": "തിരയുക",
  "seacrch": "തിരയുക",
  "secarch": "തിരയുക",
  "seaxrch": "തിരയുക",
  "sezarch": "തിരയുക",
  "seavrch": "തിരയുക",
  "sezcarch": "തിരയുക",
  "Seattings": "ക്രമീകരണങ്ങൾ",
  "WELqCOME": "സ്വാഗതം",
  "sefardchf": "തിരയുക",
  "seafdrch": "തിരയുക",
  "seacsrch": "തിരയുക",
  "secasrch": "തിരയുക",
  "seaxrsch": "തിരയുക",
  "sezarsch": "തിരയുക",
  "seavsrch": "തിരയുക",
  "seszcarch": "തിരയുക",
};
